#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

# Make sure our monitors are set up nicely, if we know
autorandr -c

bspc monitor eDP-1 --reset-desktops slack browser k8s

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config border_width 0
bspc config focus_follows_pointer true

# Set the background
feh --bg-fill $HOME/wallpapers/data-cloud.png

xsetroot -cursor_name left_ptr &
~/.config/polybar/./launch.sh

# Load picom
picom --experimental-backends &

# Start some default programs & rules
bspc rule -r "*" # First remove all previous rules


bspc rule -a "Slack" monitor=eDP-1:^1
gtk-launch slack

bspc rule -a firefox --one-shot desktop='browser'
firefox &

bspc rule -a "openlens" desktop='k8s'

# Let's make vim actually usable
setxkbmap -option "caps:swapescape"

